### ISSUE TITLE
PWA Messenger for Phone

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-old#11]

**Comment by BearGuy** [comment]
### Research
The list of resources for mobile and PWA implementations of apps and dapps on other platforms
- https://toshi.org
- https://hype.codes/how-code-ethereum-dapps
- https://github.com/ethereum/web3.js/
- https://css-tricks.com/production-progressive-web-apps-javascript-frameworks/

### Design
- PWA that is both mobile and desktop friendly
- Written with React
- Initialized with `create-react-app`

### Functionality
- Ability to send messages, attachments, Saito transactions
- Message list to manage chat convos with multiple contacts
- Integration with wallet

### To consider
- Right now all modules are being written with jquery, which means html and and js functionality are being mixed together
- React segregates view with controller, thus needs a way to interact with blockchain network either through API or through passing functions back to server, or through Redux/Mobx
- Isomorphism will only become possible once Saito core is configured to run ES6
