### ISSUE TITLE
Tests are not included in the code base

### ISSUE THREAD

**Issue by tlkahn** [SaitoTech/saito-old#32]
I find in .gitignore

`lib/test.js`

which I suppose should be tests. Can anyone help remove this and add tests to the code base? It would be help build up the test coverage as well as make easier for new devs to understand.

Thanks!

**Comment by BearGuy** [comment]
Hey @tlkahn 

Currently we're working on a rewrite of the code that will not only make it easier for new devs to understand, but will also include complete test coverage. You can take a look at our progress over at https://github.com/trevelyan/newsaito. We'd love to get your feedback.

**Comment by trevelyan** [comment]
Yeah, although if you're interested in building modules you should feel comfortable just building them on the existing system.

We're expecting it will take us about two weeks to get the new codebase to the point where it can run the existing modules reasonably-well and get slotted in as our replacement for the current codebase here. Tests are coming though.... :D
