### ISSUE TITLE
Wrong URL when redirecting from the faucet

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#42]
![image](https://user-images.githubusercontent.com/54612963/63894068-b982ca80-c9b9-11e9-821f-5c2d59618c8c.png)

When getting tokens from the faucet, it gives you a link to go back to the mail. Said link takes you to saito.tech/mail instead of apps.saito.network/mail which results in a 404

**Comment by arpee** [comment]
I'll look at this one Tucho.

Thanks.

**Comment by arpee** [comment]
@Tuch-o - a fix for this is in place.

It can be tested after the next update.

Richard

**Comment by Tuch-o** [comment]
Great, I'll assign it to to myself for testing

**Comment by Tuch-o** [comment]
Fixed. Closing this one.
