### ISSUE TITLE
Arcade fails to show names

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#45]
![image](https://user-images.githubusercontent.com/54612963/63944584-cc3fe280-ca3f-11e9-810b-05ddd11efe68.png)
![Screenshot_2019-08-29-09-25-16-237_com chrome beta](https://user-images.githubusercontent.com/54612963/63944623-e4affd00-ca3f-11e9-88f5-7269812f736e.png)

As you can see, arcade shows invites from hashes on one of my browsers when it should be showing names, as it does on mobile

**Comment by trevelyan** [comment]
browsers now many a DNS call to fetch the identities of any unknown hashes.
