### ISSUE TITLE
Repeat invites in Arcade

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#47]
Sometimes Arcade goes haywire and this happens. Not sure what's triggering it. 
![image](https://user-images.githubusercontent.com/54612963/63952613-e1bc0900-ca4d-11e9-8bf7-39209fee933c.png)

**Comment by BearGuy** [comment]
Added timers to delete open games on the client side

**Comment by Tuch-o** [comment]
Reopening this, still happening but I think it only happens on Edge now. A refresh fixes it.

![image](https://user-images.githubusercontent.com/54612963/66134257-0879dc00-e5c6-11e9-9d15-6af1e8ca0071.png)

**Comment by trevelyan** [comment]
Closing issue as Arcade is getting re-written so fixing bugs in the old-version is a bit pointless since the code is changing anyway.
