### ISSUE TITLE
Invalid words don't disappear

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#48]
![image](https://user-images.githubusercontent.com/54612963/63979565-30d26000-ca87-11e9-97d3-7a8ead7f925a.png)

Non-playable words don't disappear after you play them, have to refresh for them to go away.

**Comment by arpee** [comment]
All right - I have fixed this issue - and added a more intuitive selector for vert/horiz choice.

Asigning back to you tucho for testing.

R

**Comment by arpee** [comment]
@Tuch-o - can you test and close if all good?

Thanks

**Comment by Tuch-o** [comment]
Confirmed fixed. Will close
