### ISSUE TITLE
There is no winner.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-old#49]
We are throwing a server side error on game deletion. Not sure if this is causing any issues.
```
|node:6561) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: no such column: winner
| (node:6561) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 70)
```

Just thought I would flag, rather than fix - as it might relate to something that is troubling folk.

@BearGuy @trevelyan

**Comment by trevelyan** [comment]
code updated so field exists in database -- will get fixed at next blockchain nuke. shd not cause problems in meantime
