### ISSUE TITLE
Warsaw Pact doesn't do anything when used to remove US influence

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#50]
This happens when using Warsaw Pact to remove US influence. Look at Europe, In USSR side, influence does get removed, but it doesn't in US' side. 

![image](https://user-images.githubusercontent.com/54612963/64067669-50d66080-cbfa-11e9-853a-46bd3514b7b3.png)

![image](https://user-images.githubusercontent.com/54612963/64067656-300e0b00-cbfa-11e9-9314-c4a99224afce.png)

**Comment by trevelyan** [comment]
Nice catch. Should be fixed now.
