### ISSUE TITLE
Ghost invite from Gegitor

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#51]
Weird bug, my main account's arcade shows a permanent invite from Gegitor that isn't actually there. Accepting it doesn't do anything. Screenshots below (2nd screenshot is incognito mode)

![image](https://user-images.githubusercontent.com/54612963/64067796-6d739800-cbfc-11e9-8a9e-ce52d1de5489.png)

![236](https://user-images.githubusercontent.com/54612963/64067811-c2171300-cbfc-11e9-9901-4d09ec05d1b1.png)

**Comment by BearGuy** [comment]
If this is is still occurring, can you send one of us your wallet to check it out?

**Comment by Tuch-o** [comment]
Actually, it disappeared today after the wallet reset. I'll open it again if it comes back.
