### ISSUE TITLE
Olympic Games gives 2 ops instead of 4

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#52]
When opponent decides to boycott the Olympics, it allows you to play only 2 ops instead of 4. Look at the log in the screenshot below.

![image](https://user-images.githubusercontent.com/54612963/64068474-97ca5300-cc06-11e9-8334-4832d9f15381.png)

**Comment by Ramcas42** [comment]
I'm going to take a look at this bug,

**Comment by trevelyan** [comment]
fixed
