### ISSUE TITLE
Moving Europe's VP counter

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#53]
Currently, Europe's VP counter looks like this:

![EuropeVP](https://user-images.githubusercontent.com/54612963/64068727-11177500-cc0a-11e9-83eb-9320f5734304.png)
As you can see there, it gets covered up by Sweden's and Finland's influence if there is any.

I recommend moving it a bit to the side to avoid this, same way SA's VP counter is a bit shifted to the right: 

![FixEuropeVP](https://user-images.githubusercontent.com/54612963/64068745-6e132b00-cc0a-11e9-840d-3ea5c7889aba.png)

**Comment by BearGuy** [comment]
Fixed, catch it in the next update
