### ISSUE TITLE
Confirmation Button in TS

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#55]
I'm my opinion, this is our most requested feature. Everyone complaints about misclicks and it would help a lot with newbies. 

Regarding its implementation, it could work like when you try couping a BG when DEFCON is 2. A box asking if you're sure that's what you wanna do. If you place influence, it could ask you to confirm after you're done placing it. Also, a "don't show this again" option would be wonderful.

**Comment by BearGuy** [comment]
Concerns about adding this feature

1. We're concerned about introducing another ~250 clicks per game, as this does take a toll in fatiguing the user.

2. Midway through the game, people still will be likely to double click through confirmation options without thinking too much about it causing misclicks.

**Comment by Tuch-o** [comment]
1. This is why I want a Don't Show This Again button.

2. You're right, and not even 5 confirmaton buttons will end misclicks whatsoever. Nonetheless, if you ask the crew, everyone wants it. 

Even if this isn't a very critical issue, it is a very popular suggestion. If you add it with a way to disable it, it shouldn't bring up more troubles.

PS: I'm still learning this GitHub thing and I hadn't noticed you answered. That's why I took so long. My bad, won't happen again :)

**Comment by BearGuy** [comment]
Duly noted, I think with an inclusion of a "Don't Show This Again" button this would be a feature that wouldn't be super intrusive.

**Comment by BearGuy** [comment]
Feature has been added!
