### ISSUE TITLE
Game wrongly shows the USSR as the winner

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#56]
Happens when USSR loses via DEFCON. It says USSR won even if the log clearly shows DEFCON dropped on USSR's turn. Pls fix so Krom stops bullying me saying he won.

Screenshot attached:
![image](https://user-images.githubusercontent.com/54612963/64352192-982d6a00-cfc9-11e9-8d5d-e3a2818ab2d3.png)

**Comment by BearGuy** [comment]
Am not able to reproduce on my side (even with defcon suicide caused by Duck and Cover), can you provide any additional information?

**Comment by trevelyan** [comment]
I fixed this. Will update.

**Comment by trevelyan** [comment]
fixed this
