### ISSUE TITLE
Chat behaving weird

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#57]
Playing a match against Krom, My Chrome window started disconnecting randomly and I had to refresh. Tried sending a message thru the chat but it told me I was disconnected and it grayed out, nonetheless, I did receive the message in my alt account (which wasn't suffering from disconnection issues). 

Screenshots attached, 26p6 is my main account.

Chrome
![Chome](https://user-images.githubusercontent.com/54612963/64349643-4e428500-cfc5-11e9-8ca0-f9a407471d3c.png)

Edge
![Edge](https://user-images.githubusercontent.com/54612963/64352730-8dbfa000-cfca-11e9-8554-305f1f3876b3.png)

**Comment by BearGuy** [comment]
This doesn't seem like a bug to me, just issues with connections between browsers
