### ISSUE TITLE
China card giving an extra influence point

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#58]
Krom (USSR) controlled Italy 0/2. I used China to break control and I still had 3 influence left. Ended up 3/2 when it should have been 2/2. Look at the log 

Screenshot attached: 
![Italy](https://user-images.githubusercontent.com/54612963/64359277-02e4a280-cfd6-11e9-9b49-85770b04e8fb.png)

**Comment by BearGuy** [comment]
This is expected behaviour. 2 influence to break control --> (1 | 2), then +2 additional influence to reach (3 | 2)
