### ISSUE TITLE
Tokens disappearing from wallet

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#59]
Tried sending an invite but it told me I didn't have enough tokens, which I found weird since I had sent another invite an hour earlier. In the main page, it showed me 0 tokens. Went to the faucet and claimed the tokens but didn't receive any. After reloading a couple times, my balance showed up again.

Screenshots attached:

![image](https://user-images.githubusercontent.com/54612963/64386907-625ba600-d008-11e9-8cb3-198c2d4d3fc8.png)

![image](https://user-images.githubusercontent.com/54612963/64387203-46a4cf80-d009-11e9-932d-f23dbcb60b17.png)

**Comment by trevelyan** [comment]
lets focus on bigger issues and assume this is an edge case for now.
