### ISSUE TITLE
Chess move showing up in TS log

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#62]
I think this happened bc I had sent a Chess invite before I took Saitopore's TS game and then an Organic (that later played Krom) took it. Being able to close invites would resolve this.

![image](https://user-images.githubusercontent.com/54612963/64711964-7845ec80-d488-11e9-8fbe-eb8b107a1c0d.png)

**Comment by trevelyan** [comment]
I believe I have solved this, although it will not update until the server code updates in maybe 24 hours.
