### ISSUE TITLE
TS Freeze

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#63]
Had a game against Saitopore freezing today, really important. Screenshot and report attached. 

PS: Can you please add the hash under your opponent's name in the Player tab? Would make it easier to find transactions in the explorer. I couldn't ask Saitopore his hash since he had already left.

[T006- Bug Report.docx](https://github.com/SaitoTech/saito/files/3601992/T006-.Bug.Report.docx)

![image](https://user-images.githubusercontent.com/54612963/64719966-5ef86c80-d497-11e9-8547-52a91cafe3ee.png)

**Comment by BearGuy** [comment]
David pushed a change to address this. Should be fixed.
