### ISSUE TITLE
Asia Scoring bug

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#64]
Credit to Cardlinger for finding this bug.

He (USSR) controlled Taiwan and had Dominaton in Asia but the Scoring only gave him 1 vp, when it should have been 5. After I played China, thus cancelling Formosan, it went back to -5.

**Comment by Tuch-o** [comment]
UPDATE:

Not sure if Formosan Revolution is what's causing it since it got cancelled but this happened later when Asia was scored, look at the log:

![image](https://user-images.githubusercontent.com/54612963/64876253-bd9b2300-d61c-11e9-9d96-8bd718a0b8bb.png)

**Comment by BearGuy** [comment]
Double checked, looks like there were a few bugs in the core logic for calculating Asia scoring. Let's be on the lookout to see if this fixes it.

**Comment by Tuch-o** [comment]
Reopening this as more miscalculations have surfaced. Quoting Duke:

adjacency is not being factored into the vp counter, at least not in asia. Should be 9 from control + 6 from bg + 2 from adjacency to a total of 17. The scoring card gets it right.

Screenshot Attached
![unknown-1](https://user-images.githubusercontent.com/54612963/66011175-0d3c7400-e490-11e9-9ef3-e511a29598d2.png)

**Comment by trevelyan** [comment]
This was sort of hilarious.

It wasn't an adjacency issue. The game wasn't even bothering to check to see if anyone had control over Asia. Takes a Cardlinger to find that one.

Fixed.
