### ISSUE TITLE
Make back button undo influence

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#65]
When placing influence, the back button should undo what you've already placed. This can be done rn refreshing the page but implementing it would improve the game experience.

Screenshot attached with an absolutely innecessary red circle.

![BackButtonn](https://user-images.githubusercontent.com/54612963/64870395-30060600-d611-11e9-89fe-9fb25fc6863c.png)

**Comment by BearGuy** [comment]
Feature has been added  🎉 Try testing it out!
