### ISSUE TITLE
"Success" screen stays after the invite has expired.

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#70]
Not sure if the title explains it. This is what I'm talking about:

![image](https://user-images.githubusercontent.com/54612963/65164889-b6ed2100-da0b-11e9-8612-e247f6396ba6.png)

If you look at the screenshot, there's no invite from that hash. (the other 2 are my alts)

Once the invite you've sent expires, that screen should go as well and the user should be sent back to the Arcade. You could also add a button to extend the invite.

**Comment by arpee** [comment]
Why not close it? If you haven't closed it for 15 minutes - maybe you are still reading it?

**Comment by arpee** [comment]
Do you think the close option is not obvious enough?

**Comment by trevelyan** [comment]
I'm closing this report because there is a close button right on the screen.
