### ISSUE TITLE
Log shows 10002 VP

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#73]
Old bug here. When someone scores Europe domination, log shows 10002 vp. It should probably say something like "WIN", like it does on the Europe VP preview.

Where's the screenshot? Attached

![EuropeVP](https://user-images.githubusercontent.com/54612963/65263000-8ecbf380-dad9-11e9-9364-2f605692fd92.png)

**Comment by BearGuy** [comment]
Added
