### ISSUE TITLE
Back button doesn't appear when playing opponent's event

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#74]
More back button goodness pls. This is what I mean

![image](https://user-images.githubusercontent.com/54612963/65340426-2eea5100-db9c-11e9-9db1-9c83cd19a6b4.png)

_Screenshot attached_

**Comment by trevelyan** [comment]
will look for this my next game....

**Comment by trevelyan** [comment]
Fixed.

Feature will appear with next update of Twilight Struggle module.
