### ISSUE TITLE
Latin American Death Squads trigger outside of Latin America

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#75]
Those death squads have some reach. Look at the log, I got a -1 on an Iran coup. 

Is the screenshot attached? Of course it is.

![image](https://user-images.githubusercontent.com/54612963/65340792-01ea6e00-db9d-11e9-97b8-ed79fe28de6c.png)

**Comment by trevelyan** [comment]
Yeah, that's the direct reading of the card, so it's how it is
implemented....

**Comment by Tuch-o** [comment]
But afaik it should be Americas only

https://twilightstrategy.com/2012/11/09/latin-american-death-squads/
https://boardgamegeek.com/thread/446401/latin-american-death-squads-opponents-penalty

**Comment by trevelyan** [comment]
Yeah. But we'd get complaints the other way if we changed it.

**Comment by trevelyan** [comment]
And the straight reading of the card is -1 everywhere else, which sort of
makes more sense as a card tbh.

**Comment by Tuch-o** [comment]
I understand, feel free to close it

**Comment by trevelyan** [comment]
closing - not a bug :)
