### ISSUE TITLE
Chat doesn't show up on mobile

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#76]
I have a Xiaomi. Using Xiaomi's default browser I can't see the chat. It does show up on mobile chrome tho so it might be an issue with the browser but you know, always important to improve compatibility. 

附加屏幕截图 (not sure if that's right lol)

![Screenshot_2019-09-23-09-29-41-089_com android browser](https://user-images.githubusercontent.com/54612963/65429937-0608cc80-dde5-11e9-91d9-254392bba894.png)

**Comment by trevelyan** [comment]
Closing this as it will be affected by the new Arcade / Game Engine redesign.
