### ISSUE TITLE
Mobile - Asks me to register a name when I already have one

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#77]
Pretty self-explanatory. I'm already mtucho (mobile tucho). So it probably shouldn't be asking me to register a name. Is it even possible to change your name after you've set it?

I'm running out of ways to say the screenshot is attached but here it is 

![Screenshot_2019-09-23-11-50-07-868_com chrome beta](https://user-images.githubusercontent.com/54612963/65441919-407c6480-ddf9-11e9-8248-bed1c2bee77c.png)

**Comment by arpee** [comment]
Just checking here - the messages in chat were sent from mobile?

**Comment by Tuch-o** [comment]
Indeed

**Comment by trevelyan** [comment]
This is a good point.

I'm closing because this flow will be changed with the upcoming version, so we shouldn't worry about fixing the old one.
