### ISSUE TITLE
Frozen Game against Cardlinger

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#78]
My internet died while playing a match against Cardlinger, I rebooted my modem and it came back, must have been less than 2 minutes without conection. 

The game was dealing the cards when the disconnection happened, starting T8. After my connection returned, the cards loaded and I managed to pick Cultural Diplomacy as headline but then it got stuck again, not advancing this time. Should also be noted that the chat went blank and never worked after the disconnection. 

Console showed the following error:

TypeError: Cannot read property 'ops' of undefined
    at Twilight.playHeadlineModern (browser.js:41087)
    at Twilight.handleGame (browser.js:40420)
    at Twilight.runQueue (browser.js:15719)
    at Twilight.initializeGameFeeder (browser.js:16337)
    at Twilight.initialize (browser.js:15880)
    at Mods.initialize (browser.js:7417)
    at initSaito (browser.js:395483)

Last block found in the explorer, 35967, I'm 26p6

Screenshot attached too:

![image](https://user-images.githubusercontent.com/54612963/65532479-ded7fb00-dec9-11e9-8e27-4e9e0774ce1e.png)

Let me know if you need anything else

**Comment by trevelyan** [comment]
Thanks a lot, Tucho.

Going to see what I can do about this.

Is the new code, which is a good sign.

**Comment by trevelyan** [comment]
i think solved.

**Comment by trevelyan** [comment]
good job with screenshot and info btw. was easy to find relevant line in code.
