### ISSUE TITLE
Hitting the back button when playing Grain Sales to Soviets sends you to the card selection screen

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#79]
Title might not be clear, when you get the option to play or return the card you received with Grain Sales, you can hit the back button and the following happens:

![image](https://user-images.githubusercontent.com/54612963/65611614-105fcd80-df81-11e9-92b3-25f87c900c77.png)

Should be noted that I'm not sure what happens if you actually try to play another card, I was playing an organic so I tried refreshing instead to see if that fixed it, which it did.

Screenshot attached

**Comment by trevelyan** [comment]
@BearGuy - can you take a look at this?

We shouldn't be able to go back if the event has already triggered

**Comment by trevelyan** [comment]
fixed
