### ISSUE TITLE
Node not syncing if no peers listed.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-old#8]
1. Create a node and start to generate cash.
1. Send messages to generate blocks.
1. Add second node that lists one as a peer.
> Two syncs.
4. Stop one
5. Send messages on two to generate blocks.
6 Restart one.
> Error
One does not add blocks from two.

**Comment by trevelyan** [comment]
I cannot replicate this with a two-node setup on my own computer. Are you sure that you are using the latest version of the code on both nodes? Process followed:

1. Start Node 1 and produce N blocks
2. Start Node 2 ==> (it sync N blocks)
3. Stop Node 1
4. Produce M blocks on Node 2
5. Start Node 1 ==> (it syncs M blocks)
6. Produce 1 block on Node 2 ===> (Node 1 syncs 1 block)
7. Produce 1 block on Node 1 ===> (Node 2 syncs 1 block)


With that said, if we are debugging and able to replicate this problem, one useful thing to know is whether a node just fails to sync on reboot, or whether the problem persists even if the other nodes are producing blocks on the longest chain.

A useful debugging strategy is to add a console.log output in the peer.js class in the function which receives "block available". This allows for command-line confirmation that the node has received a notification from other node about a new block, and can be used to figure out which are software issues and which may be network issues (lack of connectivity, etc.)

**Comment by arpee** [comment]
This is working no public instances on Digital Ocean - so long as one node lists the other as a peer using its FQDN or Public IP
