### ISSUE TITLE
Invites can be sent without tokens on mobile 

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#80]
Quoting Recc:

Just found an interesting bug, I was creating an invite from my phone and it went tru as a chat invite, but that account has 0 saito since the wallet reset. When I put my browser on desktop mode, I got the classic error of not enough saito to post a game.

Both Darkuso and I tried to take one of those invites, none loaded. We think this might explain ninjas

No screenshot attached this time :(

**Comment by trevelyan** [comment]
This is a useful bug to flag.

I'm going to close it because it will be a bit of a pain to fix presumably and we should take that time on the new version instead of patching the old version.

We will make sure this issue is not present in the next version.
