### ISSUE TITLE
Game invite notification looks awful on mobile 

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#81]
/r/titlegore 

This is what I mean, look at this attached screenshot. You'd miss there's an open invite if you weren't paying attention

![Screenshot_2019-09-29-21-13-47-381_com discord](https://user-images.githubusercontent.com/54612963/65843218-75f3e700-e2fe-11e9-9c41-354ecfa1578c.png)

**Comment by trevelyan** [comment]
lol

**Comment by trevelyan** [comment]
Deleting as we are fixing this with the new version, so there won't be changes to the current one.
