### ISSUE TITLE
"Disconnected from chat, refresh your browser" error

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#83]
So this happens only when my PC is disconnected from the internet for a couple hours. I reconnect it and the red stripe from chat disappears, I can refresh the site and receive messages but I can't send them. Only way to fix it is to close the browser and then open it again, and it only happens on Chrome. Using Edge I can just reconnect and everything works just fine.

Screenshots (2 this time lol) attached:
![image](https://user-images.githubusercontent.com/54612963/66078000-21837e00-e52f-11e9-8d92-1b6db5d0112f.png)

Chatbox grays out after showing the error:
![image](https://user-images.githubusercontent.com/54612963/66078046-3eb84c80-e52f-11e9-9801-64065e2d0836.png)

**Comment by trevelyan** [comment]
if this is browser-specific to Chrome, it isn't going to be something we can fix.

We are overhauling the way browsers and modules handle disconnection / reconnection events. And there will be electron versions of Saito that avoid this issue as well. So closing for now.
