### ISSUE TITLE
Ortega Elected in Nicaragua lets you coup a country without influence

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#85]
Credit to Ramko.

Title is pretty self-explanatory, look at the good ole attached screenshot:

![06c9888061](https://user-images.githubusercontent.com/54612963/66093553-bea9db00-e55e-11e9-8bff-6c25da68e261.jpg)

As you can see, there was no change from the coup and Honduras shows 0 influence.

**Comment by trevelyan** [comment]
interesting edge case there....

will put on the back burner for the moment as am working on the latest
version of the js core.

lets leave this up and I'll tackle it when I have some time.

**Comment by trevelyan** [comment]
Fixed.

As long as there was a VALID coup target, all three neighbours were being permitted as coup targets. This is now fixed.
