### ISSUE TITLE
Game shows Opponent Resigned when he didn't

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#89]
Game-breaking bug, has been reported already by a couple of guys. Idk what triggers it, but the game shows the opponent has resigned out of nowhere. Just happened to me in Chess against Exegesis. Also happens in TS.

Screenshot attached:
![image](https://user-images.githubusercontent.com/54612963/66655139-929af380-ec09-11e9-9adb-26b7356ab6d5.png)

Look at the log, I refreshed after the first Opponent Resigned message and it went away so I managed to play. After that move I couldn't do anything.

Found the last block: 26164 (Exegesis is M95)

**Comment by trevelyan** [comment]
My guess is that "gameover" messages from one game are triggering issues in another?

Closing this as the way that the arcade and games handle gameover messages will change and be easier to fix in the new version. And we need to debug that one to ensure that it handles everything properly anyway.
