### ISSUE TITLE
Font-Awesome 

### ISSUE THREAD

**Issue by trevelyan** [SaitoTech/saito-old#9]
we are remote-loading a library we need to include in-house, at least for chrome extension purposes.

**Comment by sebs** [comment]
these are on npm, at least the google fonts are.

**Comment by escapedcat** [comment]
yup, https://github.com/FortAwesome/Font-Awesome

**Comment by trevelyan** [comment]
Just as a heads up -- it is probably preferable to link directly to
libraries hosted as part of the distribution rather than relying on NPM
includes. We can always have scripts that swap out those links for CDN
materials.

Why? Using NPM-bundled scripts (i.e. socket.io, font-awesome) mean that the
scripts are not available when we need to convert the Saito application
into javascript. It also requires making more complicated changes to
multiple files (HTML as well as JS). The reason for this is that extensions
(at least in chrome) can only run javascript that is bundled together with
the HTML files that are stored offline. So we need the files locally anyway.

We have the same issue with socket.io FWIW. I'm planning to inline the
javascript for that as a default library instead of linking through the NPM
module.

**Comment by trevelyan** [comment]
This is irrelevant for server-hosted modules, but it will make a difference
for any module that needs / wants to have a user-interface, either on a
separate webpage or as part of the default email install.

**Comment by sebs** [comment]
Thanks for the answer. Reasonable ;)
