### ISSUE TITLE
US didn't got dealt cards

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#91]
Playing a bugtesting match against myself, this happened. Starting T6 and I only have 2 cards. USSR didn't have this issue. There seemed to be no errors in the console, deck lengths were the same in both browsers.

I've had awful connection this whole match. Might be the cause.

Last transaction was found in block 36840. kabz is the incognito window I was using (USSR)

![image](https://user-images.githubusercontent.com/54612963/66995010-3c600180-f09c-11e9-8378-438cfaff2e4b.png)

**Comment by Tuch-o** [comment]
Match got stuck starting Turn 7, showed me "Us fetching new cards" and didn't advance from there

**Comment by trevelyan** [comment]
Bad connection is definitely the cause.

This is an important bug -- but I am going to shelve it as we are updating the backend SAGE game engine and that includes deal handling and how games are saved. We will focus on bug-fixing that version once it is live.

We will probably have an uptick in these sorts of problems, and then hopefully eliminate them to zero in the new version, as there will be much more standardization in how games handle deals / etc. with the stack.
