### ISSUE TITLE
Frozen TS game

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#93]
Match between Gegitor and Telechris.

Quoting Gegitor:
Got frozen while playing TS - when I played Brush War for the event and refreshed the browser before picking a target country (there was some delay after I confirmed that I wanted the event), it got stuck on displaying message "rebroadcasting our last move..."

Match didn't continue even after sending emails to himself and restoring the game.

Last transaction: Block 46865 (Telechris is 27s)

**Comment by trevelyan** [comment]
I'll see if I can replicate this, thx.

**Comment by trevelyan** [comment]
Not able to replicate.

We seem to have only a few of these issues. Believe the next version of the Game Engine will make it easier to solve / debug so will close for now.
